import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.scss";
import Header from "@/components/common/header/Herder";
import LoginModal from "@/components/common/modal/LoginModal";
import AuthSession from "@/app/AuthSession";
import UpdateStore from "@/components/updateStore";

const inter = Inter({ subsets: ["latin"] });

const notoSansKr = Noto_Sans_KR({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansKr.className}>
        <AuthSession>
          <UpdateStore />
          {children}
          <Header></Header>
        </AuthSession>
        <LoginModal />
      </body>
    </html>
  );
}
